### ISSUE TITLE
Package stability

### ISSUE THREAD

**Issue by bkamins** [pat-alt/ConformalPrediction.jl#54]
Hi,

I want to introduce this package to teaching. I know you warn that the API is not stable, but I wanted to check if this warning is serious or just a safety belt and you mostly worked out the required design?

**Comment by pat-alt** [comment]
Hi @bkamins,

that's cool to hear, thanks! The warning is more of a safety belt in case people want to start using the package in production. I don't foresee any major changes to the frontend API, since everything this interfaced to MLJ.jl. 

Let me know how everything goes or if any more questions come up as you start using the package for teaching.

Thanks

**Comment by bkamins** [comment]
Sure - I will let you know! Thank you!
